"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useParams } from "next/navigation";

type Side={sideKey:"A"|"B";score:number;participants:{player?:{gamertag:string}|null;team?:{name:string}|null;displayName?:string|null}[]};
type Match={id:string;round:string|null;status:string;playerOneScore:number;playerTwoScore:number;sides:Side[];station?:{label:string}|null};
export default function MatchesAdminPage(){const {tournamentId}=useParams<{tournamentId:string}>();const [matches,setMatches]=useState<Match[]>([]);const [error,setError]=useState("");
 async function load(){const r=await fetch(`/api/matches?${new URLSearchParams({tournamentId})}`,{cache:"no-store"});const j=await r.json();if(r.ok)setMatches(j.matches??j);else setError(j.error??"Unable to load matches");}
 useEffect(()=>{void load()},[tournamentId]);
 async function patch(id:string,body:Record<string,unknown>){const r=await fetch(`/api/matches/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));if(!r.ok)setError(j.error??"Score update failed");else await load();}
 const name=(s?:Side)=>s?.participants?.map(p=>p.player?.gamertag??p.team?.name??p.displayName??"Participant").join(" / ")??"TBD";
 return <main className="min-h-screen bg-arena-950 px-6 py-8"><div className="mx-auto max-w-7xl"><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><Link href={`/admin/tournaments/${tournamentId}`} className="font-mono text-xs text-ink-faint">← Tournament admin</Link><h1 className="mt-2 font-display text-3xl uppercase">Live scoring</h1><p className="text-sm text-ink-faint">Score any generic match using Side A / Side B. Rules and participant type come from the competition engine.</p></div><Link href={`/admin/tournaments/${tournamentId}/competition`} className="action-secondary">View rules</Link></div>{error&&<button onClick={()=>setError("")} className="mb-4 w-full rounded-card border border-signal-error/50 bg-signal-error/10 p-3 text-left text-sm text-signal-error">{error} · dismiss</button>}<div className="space-y-3">{matches.map(m=>{const a=m.sides.find(s=>s.sideKey==="A");const b=m.sides.find(s=>s.sideKey==="B");return <article key={m.id} className="rounded-card border border-arena-700 bg-arena-900 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-mono text-[10px] uppercase text-ink-faint">{m.round??"Match"} · {m.station?.label??"Unassigned"}</p><h2 className="font-display text-lg uppercase">{name(a)} <span className="text-ink-faint">vs</span> {name(b)}</h2></div><span className="rounded px-2 py-1 font-mono text-[10px] uppercase">{m.status}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><SideEditor label={name(a)} score={a?.score??m.playerOneScore} onScore={(score)=>void patch(m.id,{sideScores:{A:score}})} /><SideEditor label={name(b)} score={b?.score??m.playerTwoScore} onScore={(score)=>void patch(m.id,{sideScores:{B:score}})} /></div><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>void patch(m.id,{status:"LIVE"})} disabled={m.status==="LIVE"} className="action-secondary disabled:opacity-40">Start Live</button><button onClick={()=>void patch(m.id,{winnerSideKey:"A",status:"COMPLETED"})} className="action-secondary">A wins</button><button onClick={()=>void patch(m.id,{winnerSideKey:"B",status:"COMPLETED"})} className="action-secondary">B wins</button></div></article>})}{matches.length===0&&<p className="rounded-card border border-arena-700 p-6 text-sm text-ink-faint">No matches found.</p>}</div></div></main>}
function SideEditor({label,score,onScore}:{label:string;score:number;onScore:(n:number)=>void}){return <div className="rounded-card border border-arena-700 bg-arena-950 p-3"><div className="flex items-center justify-between gap-3"><span className="truncate text-sm">{label}</span><span className="font-display text-2xl">{score}</span></div><div className="mt-3 flex gap-2"><button onClick={()=>onScore(Math.max(0,score-1))} className="action-secondary">−1</button><button onClick={()=>onScore(score+1)} className="action-primary">+1</button></div></div>}
