import { randomBytes } from "node:crypto";
import { db } from "@/lib/db";
import { decryptBroadcastSecret, encryptBroadcastSecret } from "@/lib/broadcast/managed-kms";

const GOOGLE_TOKEN_URL = "https://oauth2.googleapis.com/token";
const GOOGLE_AUTH_URL = "https://accounts.google.com/o/oauth2/v2/auth";
const YOUTUBE_API = "https://www.googleapis.com/youtube/v3";
const OAUTH_STATE_MAX_AGE_SECONDS = 10 * 60;
const OAUTH_STATE_COOKIE = "fgc_youtube_oauth_state";

type YouTubeConnection = { connected: true; channelId?: string; channelName?: string; connectedAt: string; encryptedRefreshToken: string; broadcast?: { broadcastId: string; streamId: string; streamName?: string; videoId?: string; status?: string } };
type OAuthState = { tournamentId: string; exp: number; nonce: string };
type Overlay = Record<string, unknown> & { youtubeConnection?: YouTubeConnection };
function requiredEnv(name: string) { const value = process.env[name]; if (!value) throw new Error(`Missing required environment variable ${name}`); return value; }
function encode(value: string) { return Buffer.from(value, "utf8").toString("base64url"); }
function decode(value: string) { return Buffer.from(value, "base64url").toString("utf8"); }
export function youtubeOAuthCookieName() { return OAUTH_STATE_COOKIE; }
export function createYouTubeOAuthState(input: Pick<OAuthState, "tournamentId">) { return encode(JSON.stringify({ ...input, nonce: randomBytes(24).toString("base64url"), exp: Math.floor(Date.now() / 1000) + OAUTH_STATE_MAX_AGE_SECONDS })); }
export function verifyYouTubeOAuthState(value: string): OAuthState { let parsed: OAuthState; try { parsed = JSON.parse(decode(value)) as OAuthState; } catch { throw new Error("Invalid YouTube OAuth state"); } if (!parsed.tournamentId || !parsed.nonce || !parsed.exp || parsed.exp < Math.floor(Date.now() / 1000)) throw new Error("Expired YouTube OAuth state"); return parsed; }
export async function encryptRefreshToken(refreshToken: string, vercelOidcToken: string) { return encryptBroadcastSecret(refreshToken, vercelOidcToken); }
export async function decryptRefreshToken(value: string, vercelOidcToken: string) { return decryptBroadcastSecret(value, vercelOidcToken); }
export function youtubeRedirectUri() { return `${requiredEnv("NEXT_PUBLIC_APP_URL").replace(/\/$/, "")}/api/broadcast/youtube/callback`; }
export function youtubeAuthorizationUrl(state: string) { const params = new URLSearchParams({ client_id: requiredEnv("YOUTUBE_CLIENT_ID"), redirect_uri: youtubeRedirectUri(), response_type: "code", access_type: "offline", prompt: "consent", scope: "https://www.googleapis.com/auth/youtube", state }); return `${GOOGLE_AUTH_URL}?${params.toString()}`; }
async function exchangeCode(code: string) { const response = await fetch(GOOGLE_TOKEN_URL, { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ code, client_id: requiredEnv("YOUTUBE_CLIENT_ID"), client_secret: requiredEnv("YOUTUBE_CLIENT_SECRET"), redirect_uri: youtubeRedirectUri(), grant_type: "authorization_code" }), cache: "no-store" }); const data = await response.json().catch(() => ({})); if (!response.ok || !data.refresh_token) throw new Error(`YouTube OAuth exchange failed (${response.status})`); return data as { refresh_token: string; access_token?: string }; }
async function youtubeChannel(accessToken: string): Promise<{ channelId?: string; channelName?: string }> { const response = await fetch(`${YOUTUBE_API}/channels?part=snippet&mine=true`, { headers: { Authorization: `Bearer ${accessToken}` }, cache: "no-store" }); const data: { items?: Array<{ id?: string; snippet?: { title?: string } }> } = await response.json().catch(() => ({})); if (!response.ok) throw new Error(`Could not read YouTube channel (${response.status})`); const channel = data.items?.[0]; return { channelId: channel?.id, channelName: channel?.snippet?.title }; }
async function youtubeRequest<T>(accessToken: string, path: string, init?: RequestInit): Promise<T> { const response = await fetch(`${YOUTUBE_API}${path}`, { ...init, headers: { Authorization: `Bearer ${accessToken}`, "Content-Type": "application/json", ...(init?.headers || {}) }, cache: "no-store" }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data?.error?.message || `YouTube API request failed (${response.status})`); return data as T; }
async function saveConnectionBroadcast(tournamentId: string, broadcast: YouTubeConnection["broadcast"]) { const state = await db.broadcastState.findUnique({ where: { tournamentId }, select: { overlay: true } }); const overlay = state?.overlay && typeof state.overlay === "object" && !Array.isArray(state.overlay) ? state.overlay as Overlay : {}; if (!overlay.youtubeConnection) throw new Error("YouTube is not connected for this tournament"); const next = { ...overlay, youtubeConnection: { ...overlay.youtubeConnection, broadcast } }; await db.broadcastState.upsert({ where: { tournamentId }, create: { tournamentId, scene: "OFFLINE", overlay: JSON.parse(JSON.stringify(next)) }, update: { overlay: JSON.parse(JSON.stringify(next)) } }); }
export async function createYouTubeBroadcast(tournamentId: string, input: { title: string; description?: string; scheduledStartTime: string; privacyStatus?: "private" | "public" | "unlisted" }, vercelOidcToken: string) { const accessToken = await getYouTubeAccessToken(tournamentId, vercelOidcToken); const broadcast = await youtubeRequest<{ id?: string; status?: { lifeCycleStatus?: string } }>(accessToken, "/liveBroadcasts?part=snippet,status,contentDetails", { method: "POST", body: JSON.stringify({ snippet: { title: input.title, description: input.description, scheduledStartTime: input.scheduledStartTime }, status: { privacyStatus: input.privacyStatus ?? "unlisted" }, contentDetails: { enableAutoStart: false, enableAutoStop: false, recordFromStart: true } }) }); if (!broadcast.id) throw new Error("YouTube did not return a broadcast id"); const stream = await youtubeRequest<{ id?: string; cdn?: { ingestionInfo?: { ingestionAddress?: string; streamName?: string } } }>(accessToken, "/liveStreams?part=snippet,cdn", { method: "POST", body: JSON.stringify({ snippet: { title: input.title }, cdn: { frameRate: "30fps", ingestionType: "rtmp", resolution: "1080p" }, contentDetails: { isReusable: false } }) }); if (!stream.id) throw new Error("YouTube did not return a stream id"); await youtubeRequest(accessToken, `/liveBroadcasts/bind?id=${encodeURIComponent(broadcast.id)}&streamId=${encodeURIComponent(stream.id)}&part=id,snippet,contentDetails,status`, { method: "POST" }); const result = { broadcastId: broadcast.id, streamId: stream.id, streamName: stream.cdn?.ingestionInfo?.streamName, videoId: broadcast.id, status: broadcast.status?.lifeCycleStatus ?? "created" }; await saveConnectionBroadcast(tournamentId, result); return { ...result, ingestionAddress: stream.cdn?.ingestionInfo?.ingestionAddress, watchUrl: `https://www.youtube.com/watch?v=${broadcast.id}` }; }
export async function transitionYouTubeBroadcast(tournamentId: string, status: "testing" | "live" | "complete", vercelOidcToken: string) { const accessToken = await getYouTubeAccessToken(tournamentId, vercelOidcToken); const state = await db.broadcastState.findUnique({ where: { tournamentId }, select: { overlay: true } }); const overlay = state?.overlay && typeof state.overlay === "object" && !Array.isArray(state.overlay) ? state.overlay as Overlay : {}; const broadcast = overlay.youtubeConnection?.broadcast; if (!broadcast?.broadcastId) throw new Error("Create a YouTube broadcast first"); const result = await youtubeRequest<{ id?: string; status?: { lifeCycleStatus?: string } }>(accessToken, `/liveBroadcasts/transition?broadcastStatus=${status}&id=${encodeURIComponent(broadcast.broadcastId)}&part=id,status`, { method: "POST" }); const next = { ...broadcast, status: result.status?.lifeCycleStatus ?? status }; await saveConnectionBroadcast(tournamentId, next); return next; }
export async function connectYouTube(tournamentId: string, code: string, vercelOidcToken: string) { const tokens = await exchangeCode(code); const channel = tokens.access_token ? await youtubeChannel(tokens.access_token) : {}; const state = await db.broadcastState.findUnique({ where: { tournamentId }, select: { overlay: true } }); const previous = state?.overlay && typeof state.overlay === "object" && !Array.isArray(state.overlay) ? state.overlay as Overlay : {}; const existing = previous.youtubeConnection; const connection: YouTubeConnection = { connected: true, channelId: channel.channelId ?? existing?.channelId, channelName: channel.channelName ?? existing?.channelName, connectedAt: new Date().toISOString(), encryptedRefreshToken: await encryptRefreshToken(tokens.refresh_token, vercelOidcToken), broadcast: existing?.broadcast }; const overlay = { ...previous, youtubeConnection: connection }; await db.broadcastState.upsert({ where: { tournamentId }, create: { tournamentId, scene: "OFFLINE", overlay: JSON.parse(JSON.stringify(overlay)) }, update: { overlay: JSON.parse(JSON.stringify(overlay)) } }); return { channelId: connection.channelId, channelName: connection.channelName }; }
export async function getYouTubeConnection(tournamentId: string) { const state = await db.broadcastState.findUnique({ where: { tournamentId }, select: { overlay: true } }); const overlay = state?.overlay && typeof state.overlay === "object" && !Array.isArray(state.overlay) ? state.overlay as Overlay : {}; const connection = overlay.youtubeConnection; if (!connection?.connected || !connection.encryptedRefreshToken) return null; return { connected: true as const, channelId: connection.channelId, channelName: connection.channelName, connectedAt: connection.connectedAt, broadcast: connection.broadcast }; }
export async function getYouTubeAccessToken(tournamentId: string, vercelOidcToken: string) { const state = await db.broadcastState.findUnique({ where: { tournamentId }, select: { overlay: true } }); const overlay = state?.overlay && typeof state.overlay === "object" && !Array.isArray(state.overlay) ? state.overlay as Overlay : {}; const connection = overlay.youtubeConnection; if (!connection?.encryptedRefreshToken) throw new Error("YouTube is not connected for this tournament"); const refreshToken = await decryptRefreshToken(connection.encryptedRefreshToken, vercelOidcToken); const response = await fetch(GOOGLE_TOKEN_URL, { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ client_id: requiredEnv("YOUTUBE_CLIENT_ID"), client_secret: requiredEnv("YOUTUBE_CLIENT_SECRET"), refresh_token: refreshToken, grant_type: "refresh_token" }), cache: "no-store" }); const data = await response.json().catch(() => ({})); if (!response.ok || !data.access_token) throw new Error(`YouTube token refresh failed (${response.status})`); return data.access_token as string; }
