"use client";

import { useEffect, useMemo, useState } from "react";
import { io } from "socket.io-client";
import { DEFAULT_OBS_SCENE_MAPPING, normalizeObsSceneMapping, type ObsSceneMapping } from "@/lib/broadcast/obs";
import { DEFAULT_MATCH_TIMELINE, getNextTimelineCue, type BroadcastCommandType, type BroadcastScene } from "@/lib/broadcast/production";

const scenes: BroadcastScene[] = ["starting-soon", "intro", "versus", "gameplay", "timeout", "replay", "winner", "champion", "brb"];
const specializedCommands: Partial<Record<BroadcastScene, BroadcastCommandType>> = { "starting-soon": "COUNTDOWN_START", intro: "INTRO_PLAY", replay: "REPLAY_PLAY", winner: "WINNER_SHOW", brb: "BRB_SHOW" };
const mappingKey = (id: string) => `fgc-broadcast-obs-mapping:${id}`;

export default function BroadcastControlRoom({ params }: { params: Promise<{ tournamentId: string }> }) {
  const [tournamentId, setTournamentId] = useState<string | null>(null);
  const [program, setProgram] = useState<BroadcastScene>("starting-soon");
  const [preview, setPreview] = useState<BroadcastScene>("gameplay");
  const [status, setStatus] = useState("READY");
  const [lastCommand, setLastCommand] = useState("None");
  const [obsMapping, setObsMapping] = useState<ObsSceneMapping>(DEFAULT_OBS_SCENE_MAPPING);
  const [cueIndex, setCueIndex] = useState(-1);
  const [timelineRunning, setTimelineRunning] = useState(false);
  const [timelineStartedAt, setTimelineStartedAt] = useState<number | null>(null);
  const [elapsedMs, setElapsedMs] = useState(0);

  useEffect(() => { void params.then(async ({ tournamentId: id }) => { setTournamentId(id); try { const raw = window.localStorage.getItem(mappingKey(id)); if (raw) setObsMapping(normalizeObsSceneMapping(JSON.parse(raw) as Partial<ObsSceneMapping>)); } catch { /* safe defaults */ } try { const response = await fetch(`/api/broadcast/state?tournamentId=${encodeURIComponent(id)}`, { cache: "no-store" }); if (!response.ok) return; const payload = await response.json() as { scene?: string; persistent?: { previewScene?: string; obsMapping?: Partial<ObsSceneMapping> } }; if (scenes.includes(payload.scene as BroadcastScene)) setProgram(payload.scene as BroadcastScene); if (scenes.includes(payload.persistent?.previewScene as BroadcastScene)) setPreview(payload.persistent?.previewScene as BroadcastScene); if (payload.persistent?.obsMapping) setObsMapping(normalizeObsSceneMapping(payload.persistent.obsMapping)); setStatus("RECOVERED"); } catch { /* realtime connection will retry */ } }); }, [params]);
  useEffect(() => { if (!tournamentId) return; const socketUrl = process.env.NEXT_PUBLIC_SOCKET_URL?.trim() || window.location.origin; const socket = io(socketUrl, { transports: ["websocket", "polling"] }); const onConnect = () => { socket.emit("join:tournament", tournamentId); setStatus("LIVE"); }; const onBroadcastUpdated = (event: { tournamentId?: string; scene?: string; commandType?: string }) => { if (event.tournamentId !== tournamentId || !scenes.includes(event.scene as BroadcastScene)) return; setProgram(event.scene as BroadcastScene); setLastCommand(`${event.commandType ?? "SCENE_SET"} · ${event.scene}`); setStatus("LIVE"); }; socket.on("connect", onConnect); socket.on("broadcast:updated", onBroadcastUpdated); socket.on("connect_error", () => setStatus("OFFLINE")); return () => { socket.emit("leave:tournament", tournamentId); socket.off("connect", onConnect); socket.off("broadcast:updated", onBroadcastUpdated); socket.off("connect_error"); socket.disconnect(); }; }, [tournamentId]);
  useEffect(() => { if (!timelineRunning || timelineStartedAt === null) return; const timer = window.setInterval(() => setElapsedMs(Date.now() - timelineStartedAt), 100); return () => window.clearInterval(timer); }, [timelineRunning, timelineStartedAt]);
  const nextCue = useMemo(() => getNextTimelineCue(DEFAULT_MATCH_TIMELINE, cueIndex), [cueIndex]);
  const currentCue = DEFAULT_MATCH_TIMELINE.cues[cueIndex] ?? null;
  async function issueCommand(scene: BroadcastScene, type: BroadcastCommandType = "SCENE_SET", nextPreview = preview) { if (!tournamentId) return false; setStatus("SYNCING"); try { const response = await fetch("/api/broadcast/command", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ tournamentId, type, scene, previewScene: nextPreview, obsMapping }) }); if (!response.ok) throw new Error("Broadcast command failed"); const result = await response.json() as { obsScene?: string }; setProgram(scene); setLastCommand(`${type} · ${scene}${result.obsScene ? ` · OBS ${result.obsScene}` : ""}`); setStatus("LIVE"); return true; } catch { setStatus("ERROR"); return false; } }
  async function takePreview() { await issueCommand(preview, specializedCommands[preview] ?? "SCENE_SET", preview); }
  async function sendCue() { if (!nextCue || !tournamentId) return; const ok = await issueCommand(nextCue.command.scene, nextCue.command.type); if (ok) setCueIndex((index) => Math.min(index + 1, DEFAULT_MATCH_TIMELINE.cues.length - 1)); }
  function startTimelineClock() { setTimelineRunning(true); setTimelineStartedAt(Date.now() - elapsedMs); setStatus("LIVE"); }
  function pauseTimelineClock() { setTimelineRunning(false); setStatus("READY"); }
  function resetTimeline() { setTimelineRunning(false); setTimelineStartedAt(null); setElapsedMs(0); setCueIndex(-1); setStatus("READY"); }
  function skipCue() { if (nextCue) setCueIndex((index) => Math.min(index + 1, DEFAULT_MATCH_TIMELINE.cues.length - 1)); }

  return <main style={{ minHeight: "100vh", background: "#07080d", color: "#f7f8ff", padding: 28, fontFamily: "Inter, system-ui, sans-serif" }}><div style={{ maxWidth: 1280, margin: "0 auto" }}>
    <header style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 24 }}><div><div style={label}>FGC BROADCAST STUDIO</div><h1 style={{ fontSize: 34, margin: "7px 0 0" }}>Production Control Room</h1><div style={{ marginTop: 7, fontSize: 12, opacity: .5 }}>MANUAL PROGRAM CONTROL · AUTOMATION ASSISTS, NEVER TAKES OVER</div></div><div style={{ display: "flex", gap: 12, alignItems: "center", fontSize: 12 }}><a href={`/broadcast/${tournamentId}/control-room/operations`} style={link}>OPERATIONS 2.0</a><a href={`/broadcast/${tournamentId}/control-room/rundown`} style={link}>RUNDOWN</a><a href={`/broadcast/${tournamentId}/control-room/multiview`} style={link}>MULTIVIEW / POV</a><a href={`/broadcast/${tournamentId}/control-room/overlay-builder`} style={link}>OVERLAY BUILDER</a><a href={`/broadcast/${tournamentId}/control-room/obs`} style={link}>OBS MAPPING</a><a href={`/broadcast/${tournamentId}/control-room/sponsors`} style={link}>SPONSORS</a><a href={`/broadcast/${tournamentId}/control-room/replay`} style={link}>REPLAY</a><span style={{ width: 8, height: 8, borderRadius: 99, background: status === "ERROR" ? "#ef4444" : status === "OFFLINE" ? "#f59e0b" : "#22c55e" }} />{status}</div></header>
    <section style={{ display: "grid", gridTemplateColumns: "1.4fr .9fr", gap: 18, marginBottom: 18 }}><div style={panel}><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}><Monitor title="PROGRAM" scene={program} live /><Monitor title="PREVIEW" scene={preview} /></div><div style={{ display: "flex", gap: 10, marginTop: 14, alignItems: "center", flexWrap: "wrap" }}><button onClick={takePreview} style={button(true)}>TAKE PREVIEW</button>{!timelineRunning ? <button onClick={startTimelineClock} style={button(false)}>START CLOCK</button> : <button onClick={pauseTimelineClock} style={button(false)}>PAUSE CLOCK</button>}<button onClick={resetTimeline} style={button(false)}>RESET</button><span style={{ marginLeft: "auto", fontSize: 12, opacity: .5 }}>{formatElapsed(elapsedMs)}</span></div></div><div style={panel}><div style={label}>PROGRAM SCENE · ONE-CLICK LIVE</div><div style={{ marginTop: 5, fontSize: 11, opacity: .45 }}>Click any scene to send it directly to Program and OBS.</div><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8, marginTop: 10 }}>{scenes.map((scene) => <button key={scene} onClick={() => { setPreview(scene); void issueCommand(scene, specializedCommands[scene] ?? "SCENE_SET", scene); }} style={{ ...button(program === scene), padding: "10px 8px", fontSize: 11 }}>{scene.replace("-", " ").toUpperCase()}</button>)}</div></div></section>
    <section style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 12, marginBottom: 18 }}><Card title="PROGRAM" value={program.toUpperCase()} /><Card title="PREVIEW" value={preview.toUpperCase()} /><Card title="OBS TARGET" value={obsMapping[program].toUpperCase()} /><Card title="LAST COMMAND" value={lastCommand} /></section>
    <section style={panel}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 16, flexWrap: "wrap" }}><div><div style={label}>PRODUCTION ASSIST</div><h2 style={{ margin: "7px 0 0", fontSize: 20 }}>Cue Timeline</h2><p style={{ margin: "5px 0 0", fontSize: 12, opacity: .5 }}>The clock and cues never change Program automatically. The operator must send each cue.</p></div><div style={{ display: "flex", gap: 8 }}><button onClick={skipCue} disabled={!nextCue} style={{ ...button(false), opacity: nextCue ? 1 : .4 }}>SKIP CUE</button><button onClick={sendCue} disabled={!nextCue} style={{ ...button(true), opacity: nextCue ? 1 : .4 }}>SEND NEXT CUE</button></div></div><div style={{ marginTop: 18, display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 8 }}>{DEFAULT_MATCH_TIMELINE.cues.map((cue, index) => { const active = index === cueIndex; const sent = index < cueIndex; return <div key={cue.id} style={{ padding: 12, borderRadius: 12, border: `1px solid ${active ? "#7c3aed" : "#252936"}`, background: active ? "#151021" : "#0a0c11", opacity: sent ? .45 : 1 }}><div style={{ fontSize: 10, opacity: .45 }}>{String(cue.atMs / 1000).padStart(4, "0")}s</div><div style={{ marginTop: 6, fontWeight: 800, fontSize: 12 }}>{cue.id.toUpperCase()}</div><div style={{ marginTop: 4, fontSize: 10, opacity: .5 }}>OBS · {obsMapping[cue.command.scene].toUpperCase()}</div></div>; })}</div>{currentCue && <div style={{ marginTop: 12, fontSize: 11, opacity: .55 }}>LAST CUE · {currentCue.id.toUpperCase()} · {currentCue.command.type}</div>}</section>
  </div></main>;
}
function formatElapsed(ms: number) { const totalSeconds = Math.max(0, Math.floor(ms / 1000)); return `${String(Math.floor(totalSeconds / 60)).padStart(2, "0")}:${String(totalSeconds % 60).padStart(2, "0")}`; }
function Monitor({ title, scene, live }: { title: string; scene: BroadcastScene; live?: boolean }) { return <div style={{ aspectRatio: "16 / 9", borderRadius: 14, background: "linear-gradient(135deg,#151822,#090a0f)", border: `1px solid ${live ? "#6d28d9" : "#252936"}`, display: "flex", flexDirection: "column", justifyContent: "space-between", padding: 16 }}><div style={{ display: "flex", justifyContent: "space-between", fontSize: 10, letterSpacing: ".14em", opacity: .55 }}><span>{title}</span>{live && <span>ON AIR</span>}</div><div><div style={{ fontSize: 28, fontWeight: 800 }}>{scene.replace("-", " ").toUpperCase()}</div><div style={{ opacity: .45, fontSize: 11, marginTop: 4 }}>FGC NATIVE BROADCAST GRAPHICS</div></div></div>; }
function Card({ title, value }: { title: string; value: string }) { return <div style={panel}><div style={label}>{title}</div><div style={{ marginTop: 8, fontSize: 14, fontWeight: 700 }}>{value}</div></div>; }
const panel = { background: "#0c0e14", border: "1px solid #252936", borderRadius: 20, padding: 20 } as const;
const label = { fontSize: 10, letterSpacing: ".15em", opacity: .45 } as const;
const link = { color: "#c4b5fd", textDecoration: "none", fontSize: 11, letterSpacing: ".12em" } as const;
const button = (active: boolean) => ({ border: "1px solid #2b2f3c", borderRadius: 9, padding: "11px 15px", background: active ? "#7c3aed" : "#11131a", color: "white", fontWeight: 700, cursor: "pointer" });
