import type { CompetitionDefinition } from "./types";

export const COMPETITION_PRESETS: CompetitionDefinition[] = [
  {
    sport: "esports",
    label: "Esports / Game",
    competitionType: "tournament",
    participantMode: "individual",
    scoringAdapter: "points",
    bestOf: 3,
    capabilities: ["live_scoring", "brackets", "standings"],
    rules: { winCondition: "highest_score" },
  },
  {
    sport: "football",
    label: "Football",
    competitionType: "league",
    participantMode: "team",
    scoringAdapter: "goals",
    bestOf: 1,
    capabilities: ["live_scoring", "standings", "round_robin", "team_roster"],
    rules: {
      periodMinutes: 45,
      winPoints: 3,
      drawPoints: 1,
      lossPoints: 0,
    },
  },
  {
    sport: "basketball",
    label: "Basketball",
    competitionType: "league",
    participantMode: "team",
    scoringAdapter: "points",
    bestOf: 1,
    capabilities: ["live_scoring", "standings", "team_roster"],
    rules: { quarters: 4 },
  },
  {
    sport: "cricket",
    label: "Cricket",
    competitionType: "league",
    participantMode: "team",
    scoringAdapter: "runs",
    bestOf: 1,
    capabilities: ["live_scoring", "standings", "team_roster"],
    rules: { innings: 1, wickets: 10 },
  },
  {
    sport: "tennis",
    label: "Tennis",
    competitionType: "tournament",
    participantMode: "individual",
    scoringAdapter: "sets",
    bestOf: 3,
    capabilities: ["live_scoring", "brackets", "standings"],
    rules: { setsToWin: 2 },
  },
  {
    sport: "badminton",
    label: "Badminton",
    competitionType: "tournament",
    participantMode: "individual",
    scoringAdapter: "sets",
    bestOf: 3,
    capabilities: ["live_scoring", "brackets", "standings"],
    rules: { setsToWin: 2 },
  },
  {
    sport: "volleyball",
    label: "Volleyball",
    competitionType: "league",
    participantMode: "team",
    scoringAdapter: "sets",
    bestOf: 5,
    capabilities: ["live_scoring", "standings", "team_roster"],
    rules: { setsToWin: 3 },
  },
  {
    sport: "table-tennis",
    label: "Table Tennis",
    competitionType: "tournament",
    participantMode: "individual",
    scoringAdapter: "sets",
    bestOf: 5,
    capabilities: ["live_scoring", "brackets", "standings"],
    rules: { setsToWin: 3 },
  },
  {
    sport: "racing",
    label: "Racing / Time Trial",
    competitionType: "challenge",
    participantMode: "individual",
    scoringAdapter: "time",
    bestOf: 1,
    capabilities: ["live_scoring", "time_trial", "standings"],
    rules: { lowestTimeWins: true },
  },
  {
    sport: "skills",
    label: "Skills Challenge",
    competitionType: "challenge",
    participantMode: "individual",
    scoringAdapter: "attempts",
    bestOf: 1,
    capabilities: ["live_scoring", "standings"],
    rules: { maxAttempts: 3 },
  },
  {
    sport: "custom",
    label: "Custom Competition",
    competitionType: "custom",
    participantMode: "mixed",
    scoringAdapter: "custom",
    bestOf: 1,
    capabilities: ["live_scoring", "standings", "brackets"],
    rules: {},
  },
];